class Locator(object):
    username = "username"
    password = "password"
    login = "//span[normalize-space()='Login']"
    platform = "//button[normalize-space()='platform']"
    xray = "//span[@class='vsm--title'][normalize-space()='Xray']"
    scans_list = "//span[normalize-space()='Scans List']"
    repo_name = "//span[contains(text(),'docker-local')]"
    uploaded_image = "//div[@class='d-flex align-items-center h-100 w-100 table-cell-search-highlight']//span[contains(text(),'alpine/3.9')]"
    policy_violations = "(//span[@id='menuItemText'])[2]"
    violations_severity = "(//*[name()='svg'][@class='margin--r-6'])[1]"
    check_total_violations = "//*[@id='app-xray']/div[1]/div/div[2]/div/div[1]/div/div[2]/div[1]/div[2]/div/div/div/section[1]/div[1]/div[1]/p"
    violations_filter = "//button[@class='el-button el-button--icon margin--l-12 multi-filters-button el-button--secondary el-button--small']"
    severity_risk = "//div[contains(text(),'Severity/Risk')]"
    critical = "/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/section[2]/section[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]"
    high = "/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/section[2]/section[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/span[1]"
    medium = "/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/section[2]/section[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/span[1]"
    low = "/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/section[2]/section[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/span[1]"
    unknown = "/html[1]/body[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/section[2]/section[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[2]/span[1]"
